# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0003_nav'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nav',
            table='axf_nav',
        ),
    ]
