# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0007_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderInfo', models.CharField(max_length=1000)),
                ('orderUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOne.User')),
            ],
            options={
                'db_table': 'axf_order',
            },
        ),
    ]
