# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderFlag',
            field=models.CharField(default='cart', max_length=20),
        ),
    ]
